# that file is used to configure 
# nginx as a reverse proxy for the FastAPI application running on port 8000.
# It forwards incoming HTTP requests to the FastAPI server.
# The configuration uses the least connections load balancing method.
# It also sets necessary headers for proper request forwarding.


events {}

http {
  upstream pop_api {
    least_conn;
    server api:8000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://pop_api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
